### ISSUE TITLE
could you add the wiki pages please? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [SuperMarcus/JRakLib#2]
I need some help integrating this awesome project into Dragonet but I don't know how to use it. So is there any documentation available or will you mind helping me integrating it?

**Comment by RazvanDu** [comment]
I can help you integrate it if you want, but I wouldn't recommand it as it's not really stable in my opinion.
I've had much better results with JRakLib which I can somewhat help you integrate althought I had to change it quite a in order to get it to work lol.

**Comment by DefinitlyEvil** [comment]
Okay, I think I am gonna wait until it's stable. ;) Thanks!
